using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace trivia_backend.Models.DTOS
{
    public class CreateQuestionDTO
    {

        // No need for Id here, as it will be generated by the database

        // The CreaterId is not needed here, as it will be set in the QuizModel
        
        // THe Creator is not needed here, as it will be set in the QuizModel

        public string? QuestionText { get; set; }
        public int Score { get; set; }

        public string? CorrectAnswer { get; set; }
        public string? WrongAnswer1 { get; set; }
        public string? WrongAnswer2 { get; set; }
        public string? WrongAnswer3 { get; set; }

    }
}